# Copyright (c) 2020 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#

[package]
name = "kata-trace-forwarder"
version = "0.0.1"
authors = ["The Kata Containers community <kata-dev@lists.katacontainers.io>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
futures = "0.3.15"
clap = { version = "4.5.40", features = ["cargo"] }
vsock = "0.2.3"
nix = { version = "0.30.1", features = ["fs", "user"] }
libc = "0.2.94"
bincode = "1.3.3"
byteorder = "1.4.3"
anyhow = "1.0.31"
opentelemetry = { version = "0.14.0", features = ["serialize"] }
opentelemetry-jaeger = "0.13.0"

# Note: this crate sets the slog 'max_*' features which allows the log level
# to be modified at runtime.
logging = { path = "../../libs/logging" }
slog = "2.5.2"

privdrop = "0.5.1"
